import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // mockServiceWorker.js is auto-generated by `npx msw init` and re-written
  // on every regen — not source to lint.
  globalIgnores(['dist', 'public/mockServiceWorker.js']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Convention for intentionally-discarded values, e.g. destructuring a
      // field off an object just to strip it: `const { x: _x, ...rest } = obj`.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { varsIgnorePattern: '^_', argsIgnorePattern: '^_', destructuredArrayIgnorePattern: '^_' },
      ],
      // Flags legitimate effect uses (IntersectionObserver fallbacks, fetch
      // loading-state, auth hydration) the same as the anti-pattern it
      // targets (mirroring props into state) — too many false positives
      // across already-verified code to be a useful gate here.
      'react-hooks/set-state-in-effect': 'off',
      // Dev-mode Fast Refresh nicety only; doesn't affect production builds
      // or correctness. Fires on every icon-library/lookup-table file in
      // this codebase (component + helper exports in one file by design).
      'react-refresh/only-export-components': 'off',
    },
  },
])
