import type { HomepageContent } from '../types/content.types.js'

// TODO: move this into a DB/CMS table once one exists — the shape below
// is deliberately what the frontend already renders, so the migration
// is copy-in-copy-out with no component changes required.
export function getHomepageContent(): HomepageContent {
  return {
    hero: {
      title: 'The Future of',
      highlight: 'Property Intelligence',
      subtitle:
        'Relaive helps you generate market-aware property appraisal narratives using AI, comparable sales data, and suburb insights.',
      metrics: [
        { value: '98.5%', label: 'Accuracy' },
        { value: '30s', label: 'Generation Time' },
        { value: '10k+', label: 'Valuations' },
      ],
    },
    features: {
      title: 'Premium Intelligence Suite',
      description:
        'Everything you need for explainable, AI-powered property valuation and market intelligence.',
      items: [
        {
          id: 'ai-valuation-engine',
          icon: 'brain',
          title: 'AI Valuation Engine',
          description:
            'Advanced machine learning models trained on millions of Australian property transactions to generate explainable and professional appraisal narratives.',
          features: [
            'AI-generated valuation narratives',
            'Automated market interpretation',
            'Investor-grade reporting',
            'Explainable confidence scoring',
            'Dynamic comparable sales analysis',
            'AI reasoning transparency',
          ],
          tags: ['Vendor Appraisals', 'Bank Valuations', 'Buyer Advisory'],
          highlight: true,
        },
        {
          id: 'market-insights',
          icon: 'bar-chart',
          title: 'Market Insights',
          description: 'Suburb analytics, demographic intelligence, and rental yield trends.',
          features: ['Suburb analytics', 'Demographic intelligence', 'Demand indicators'],
        },
        {
          id: 'trend-forecasting',
          icon: 'trend',
          title: 'Trend Forecasting',
          description: 'Predictive analytics and AI market prediction for investment opportunities.',
          features: ['Predictive analytics', 'Future suburb growth', 'Investment forecasting'],
        },
        {
          id: 'comparable-sales-intelligence',
          icon: 'map-pin',
          title: 'Comparable Sales Intelligence',
          description:
            'AI-powered similarity scoring and property clustering with interactive map overlays.',
          features: ['Nearby comparable sales', 'AI similarity scoring', 'Property clustering'],
        },
        {
          id: 'professional-reports',
          icon: 'document',
          title: 'Professional Reports',
          description:
            'Editable appraisal reports with AI-generated summaries and luxury editorial layouts.',
          features: ['Editable appraisal reports', 'PDF/DOCX export', 'Report templates'],
        },
        {
          id: 'instant-generation',
          icon: 'lightning',
          title: 'Instant Generation',
          description: 'AI-generated reports in under 30 seconds with ready-to-export outputs.',
          features: ['Reports under 30 seconds', 'Automated workflows', 'AI-assisted productivity'],
        },
      ],
    },
    about: {
      title: 'Transparent Intelligence You Can Trust',
      description:
        'Every valuation generated by Relaive is backed by explainable AI reasoning, transparent comparable sales analysis, and clear confidence indicators — so you always understand how the result was formed.',
      trustFeatures: [
        'AI reasoning breakdown',
        'Comparable sales explanation',
        'Market factor analysis',
        'Confidence indicators',
        'Human-review ready outputs',
        'Evidence-based reporting',
      ],
      banner: 'Relaive supports professional judgement. Review and edit the report before sharing.',
      valuationSteps: [
        {
          id: 'property-analysis',
          icon: 'search',
          title: 'Property Analysis',
          description: 'AI scans location, property attributes, features, and market data.',
          details:
            "Relaive analyses property details such as location, land size, bedrooms, bathrooms, and surrounding suburb information to understand the property's overall market position before generating a valuation.",
        },
        {
          id: 'comparable-retrieval',
          icon: 'compare',
          title: 'Comparable Retrieval',
          description: 'Relaive retrieves recent sales and ranks them by similarity.',
          details:
            'The system retrieves recent comparable property sales and ranks them based on similarity to support accurate and evidence-based valuation results.',
        },
        {
          id: 'market-intelligence',
          icon: 'bar-chart',
          title: 'Market Intelligence',
          description: 'The system analyses suburb trends, demographic insights, and demand signals.',
          details:
            'Relaive analyses suburb trends, buyer demand, demographic insights, and local market activity to provide smarter and more context-aware property valuations.',
        },
        {
          id: 'report-generation',
          icon: 'document',
          title: 'Report Generation',
          description:
            'AI compiles a professional appraisal narrative with evidence and confidence indicators.',
          details:
            'The AI engine combines property data, comparable sales, and market insights to generate a professional appraisal report with explainable reasoning and confidence indicators.',
        },
      ],
    },
  }
}
