import type { ReactNode } from 'react'
import { Card, CardFeatureList, CardTitle } from '../ui/card/card'
import { DropCardList, type DropCardItem } from '../ui/drop-card/drop-card'

function SearchIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="11" cy="11" r="7" stroke="currentColor" strokeWidth="1.75" />
      <path
        d="M20 20L16.5 16.5"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
      />
    </svg>
  )
}

function CompareIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <rect x="4" y="6" width="8" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
      <rect x="12" y="8" width="8" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.75" />
      <path
        d="M12 11H16M8 13H12"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
      />
    </svg>
  )
}

function BarChartIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M6 20V10M12 20V4M18 20V14"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  )
}

function DocumentIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path
        d="M8 3H16L19 6V21H5V3H8Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
      <path
        d="M8 3V6H19M9 12H15M9 16H13"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
      />
    </svg>
  )
}

function InfoIcon() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="1.75" />
      <path
        d="M12 11V16M12 8H12.01"
        stroke="currentColor"
        strokeWidth="1.75"
        strokeLinecap="round"
      />
    </svg>
  )
}

const TRUST_FEATURES = [
  'AI reasoning breakdown',
  'Comparable sales explanation',
  'Market factor analysis',
  'Confidence indicators',
  'Human-review ready outputs',
  'Evidence-based reporting',
] as const

const VALUATION_STEPS: DropCardItem[] = [
  {
    id: 'property-analysis',
    icon: <SearchIcon />,
    title: 'Property Analysis',
    description: 'AI scans location, property attributes, features, and market data.',
  },
  {
    id: 'comparable-retrieval',
    icon: <CompareIcon />,
    title: 'Comparable Retrieval',
    description: (
      <>
        <strong className="font-semibold text-relaive-navy">Relaive</strong> retrieves recent sales
        and ranks them by similarity.
      </>
    ),
  },
  {
    id: 'market-intelligence',
    icon: <BarChartIcon />,
    title: 'Market Intelligence',
    description:
      'The system analyses suburb trends, demographic insights, and demand signals.',
  },
  {
    id: 'report-generation',
    icon: <DocumentIcon />,
    title: 'Report Generation',
    description:
      'AI compiles a professional appraisal narrative with evidence and confidence indicators.',
  },
]

function InfoBanner({ children }: { children: ReactNode }) {
  return (
    <div className="flex items-start gap-3 rounded-2xl border border-relaive-secondary/25 bg-relaive-secondary/10 px-4 py-3.5 sm:px-5">
      <span className="mt-0.5 shrink-0 text-relaive-primary">
        <InfoIcon />
      </span>
      <p className="text-sm leading-relaxed text-relaive-gray">{children}</p>
    </div>
  )
}

export function AboutSection() {
  return (
    <section
      id="about"
      className="scroll-mt-20 border-t border-black/5 bg-white px-6 py-24"
    >
      <div className="mx-auto grid max-w-6xl grid-cols-1 items-start gap-12 lg:grid-cols-2 lg:gap-16">
        <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-4">
            <h2 className="text-3xl font-semibold leading-tight text-relaive-navy sm:text-4xl">
              Transparent Intelligence You Can Trust
            </h2>
            <p className="text-base leading-relaxed text-relaive-gray">
              Every valuation generated by{' '}
              <strong className="font-semibold text-relaive-navy">Relaive</strong> is backed by
              explainable AI reasoning, transparent comparable sales analysis, and clear confidence
              indicators — so you always understand how the result was formed.
            </p>
          </div>

          <CardFeatureList items={[...TRUST_FEATURES]} />

          <InfoBanner>
            <strong className="font-semibold text-relaive-navy">Relaive</strong> supports
            professional judgement. Review and edit the report before sharing.
          </InfoBanner>
        </div>

        <Card className="h-auto">
          <CardTitle>Explore Valuation Progress</CardTitle>
          <DropCardList items={VALUATION_STEPS} className="mt-5" />
        </Card>
      </div>
    </section>
  )
}
